### ISSUE TITLE
AppleWin to be included into libretro downloadable cores

### ISSUE THREAD

**Issue by zoltanvb** [audetto/AppleWin#253]
Hello,

thank you for your work on this. Would you be interested in having the libretro core included to the RetroArch downloadable cores (or precompiled packages, depending on platform)? It has been mentioned a few times on Discord, and now also here: https://github.com/libretro/RetroArch/issues/17670 

The advantage of this is that users would be able to immediately get the AppleWin core, but this can also mean a bit of extra exposure, increased user requests, and the need to keep the enabled platforms compilable.

Technically, it has a few components:
- core should have an .info file submitted to [libretro-super](https://github.com/libretro/libretro-super)
- core should be able to compile on libretro buildbot infrastructure, which, for the most platforms, is Docker based cross-compilation, I can make a try with some of the main ones
- a .gitlab-ci.yml needs to be added to the repository that controls the compilation on the libretro buildbot
- repository needs to be cloned to libretro servers (this part must be set up by libretro admins)
- optimally, also some documentation on docs.libretro.com

Let me know what you think.

**Comment by audetto** [comment]
Yes, I think it is definitely a very good idea.

This library currently compiles on Linux - mingw64 - FreeBSD - macos.
The core has only ever been tested in the first 2.

I need to understand what I can / cannot do in the build script and how to replicate the build environment myself.

And what is the best location to discuss all of this, here? elsewhere?

**Comment by zoltanvb** [comment]
The Linux (x64) build environment can be tried as:
`sudo docker run -it --rm -v "AppleWin:/build" git.libretro.com:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:xenial-gcc9 bash`
I have made some initial attempts, libboost-dev, libyaml-dev and libminizip-dev had to be installed, then build ran into problems due to xxd not being available.

**Comment by audetto** [comment]
xenial? I have seen more recent distributions.

Anyway, `xxd` is provided by `vim`.
Unfortunately static linking of `libminizip.a` is not working on xenial.

The best `cmake` command line at the moment is

`cmake .. -DBUILD_LIBRETRO=ON -G Ninja`

**Comment by zoltanvb** [comment]
The build image is indeed ancient, partly on purpose, to keep binary compatibility. But it could probably be increased to bionic (by using `git.libretro.com:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:latest`), as it was done with melonds-ds, which also installs some extra libraries:
https://github.com/JesseTG/melonds-ds/blob/5d2ece5b6d7041aa9d0a7921eee42969f8bdf8a7/.gitlab-ci.yml#L68

**Comment by audetto** [comment]
I tried to use

`git.libretro.com:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:latest`

it claims to be `VERSION="18.04.6 LTS (Bionic Beaver)"`, but it has a version of `cmake` older than

`git.libretro.com:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:xenial-gcc9`

which claims to be `VERSION="16.04.7 LTS (Xenial Xerus)"`

My repo needs 3.13.

**Comment by audetto** [comment]
Anyway, after copying the extra `ppa` from melonds-ds, I got it to compile.

Unfortunately `yaml.a` and `minizip.a` are still unusable.

Does it matter?
The core compiles ok. Am I allowed to link some `.so`?

**Comment by zoltanvb** [comment]
I believe it is usually not preferred, as it limits the portability, but it is not enforced. Here is a crude scan of dynamic libraries in current Linux x86_64 cores:
[core_dynamic_libs.txt](https://github.com/user-attachments/files/19280215/core_dynamic_libs.txt)

**Comment by audetto** [comment]
I really do not understand why Ubuntu builds static libraries without `-fPIC`: fast, but unusable!

Anyway, I have never wanted to include the source code of libraries I can get for free, and without effort.

We can postpone this issue and see what else is required.

**Comment by audetto** [comment]
I've done a lot of cleanup both in libretro integration and in the build system.

This branch https://github.com/audetto/AppleWin/tree/xenial-build

generates a very clean core.

```
root@eacfc3eebca2:~/AppleWin# ll build/source/frontends/libretro                     
total 8212
drwxr-xr-x 3 root root    4096 Mar 23 10:04 ./
drwxr-xr-x 4 root root    4096 Mar 23 10:03 ../
drwxr-xr-x 3 root root    4096 Mar 23 10:03 CMakeFiles/
-rw-r--r-- 1 root root     350 Mar 23 10:03 applewin_libretro.info
-rwxr-xr-x 1 root root 8385608 Mar 23 10:04 applewin_libretro.so*
-rw-r--r-- 1 root root    1259 Mar 23 10:03 cmake_install.cmake

root@eacfc3eebca2:~/AppleWin# ldd build/source/frontends/libretro/applewin_libretro.so
	linux-vdso.so.1 =>  (0x00007fff88396000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007dcdb3c47000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007dcdb393e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007dcdb3574000)
	/lib64/ld-linux-x86-64.so.2 (0x00007dcdb47c3000)
```

What is the next step?

**Comment by zoltanvb** [comment]
Wow, great! Thank you for the efforts, I reproduced the build with minimal effort.

Next step could be reproducing 64-bit Windows builds, it is done using cross-compiling with another Docker image: `git.libretro.com:5050/libretro-infrastructure/libretro-build-mxe-win-cross-cores:gcc11`. Also, I plan to take a look at producing an Android build (it was requested here: https://forums.libretro.com/t/apple-ii-core-for-android/47480 ), it may need a few extra files but hopefully nothing that interferes with existing code.

**Comment by audetto** [comment]
How do I use it?

```
docker run -it --rm -v git.libretro.com:5050/libretro-infrastructure/libretro-build-mxe-win-cross-cores:gcc11 bash
```

tells me

`docker: Error response from daemon: invalid mode: gcc11.`

**Comment by audetto** [comment]
now this works

```
docker run -it --rm -v "AppleWin:/build" git.libretro.com:5050/libretro-infrastructure/libretro-build-mxe-win-cross-cores:gcc11 bash
```

but I have no idea what to do with it.

is there any help on all of these target environments?

**Comment by zoltanvb** [comment]
Hi, sorry for the long feedback times. This container is using Bionic, but the cmake version is still too old, I was able to make first steps with:

```
apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget
wget -qO - https://apt.kitware.com/keys/kitware-archive-latest.asc | apt-key add -
apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
apt-get update
apt-get install cmake
apt install libboost-dev
ln -s /usr/bin/ninja /usr/local/bin/ninja

```
For some reason, ninja is present, but in a different location, hence the linkage.

**Comment by zoltanvb** [comment]
Oops, no, this will try a Linux binary... Cmake should be invoked like:
`x86_64-w64-mingw32.static-cmake`

**Comment by audetto** [comment]
Fine. If you explain me what the goal is, I can try to help.

I understand there is a x-compiler `cmake`, but how do I install cross compiler packages?

**Comment by audetto** [comment]
I suspect the only missing package is boost, but I have not found how to install it.

**Comment by zoltanvb** [comment]
This seems to bring a few:
```
    echo "deb http://pkg.mxe.cc/repos/apt bionic main" > /etc/apt/sources.list.d/mxeapt.list
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C6BF758A33A3A276
    apt-get update
```

Maybe the needed one is `mxe-x86-64-w64-mingw32.static-boost` .

**Comment by gouchi** [comment]
The mxe packages currently available in the image are
`cc cmake bzip2 curl gcc glib gmp gnutls libpng nettle pixman pkgconf dlfcn-win32 libsndfile sdl_net sdl2 zlib libxml2 freetype fribidi ninja nasm`

[Source](https://git.libretro.com/libretro-infrastructure/libretro-build-mxe-win-cross-cores/-/blob/fb98d96078250a582ada5d30ee67e503c4358250/Dockerfile.gcc11#L82-L103).

Using [xenial-build](https://github.com/audetto/AppleWin/tree/xenial-build) branch

```
docker run -it --rm -v "/path/to/AppleWin:/build" git.libretro.com:5050/libretro-infrastructure/libretro-build-mxe-win-cross-cores:gcc11 bash
cd build
/usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-cmake -DBUILD_LIBRETRO=ON -B build -G Ninja
```
I get this result

<details>
  <summary>Log</summary>

```
== Using MXE wrapper: /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-cmake
     - cmake version 3.23.1
     - warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /usr/lib/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /usr/lib/mxe/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /usr/lib/mxe/usr/share/cmake/modules/TryRunResults.cmake
CMAKE_BUILD_TYPE:                Release
CMAKE_CXX_FLAGS:                 
CMAKE_CXX_FLAGS_RELEASE:         -O3 -DNDEBUG
CMAKE_CXX_FLAGS_DEBUG:           -g
CMAKE_CXX_FLAGS_RELWITHDEBINFO:  -O2 -g -DNDEBUG
CMake Warning at source/CMakeLists.txt:14 (message):
  'libslirp' not found: will try 'libpcap' instead


-- Checking for one of the modules 'libpcap'
CMake Error at /usr/lib/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/lib/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/lib/mxe/usr/x86_64-pc-linux-gnu/share/cmake-3.23/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
  source/CMakeLists.txt:34 (find_package)


-- Configuring incomplete, errors occurred!
See also "/build/build/CMakeFiles/CMakeOutput.log".
```

</details> 

Using `apt install mxe-x86-64-pc-linux-gnu-boost` after [adding apt repository](https://github.com/audetto/AppleWin/issues/253#issuecomment-2770587380). CMake still can't find it.

To be continued ;)

**Comment by audetto** [comment]
With

`apt install mxe-x86-64-w64-mingw32.static-boost`

then `cmake` works, but `gcc` is too old.

```
root@78fbd2e5cd1f:/build/AppleWin/build# /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-gcc --version
x86_64-w64-mingw32.static-gcc (GCC) 5.5.0
```

how do I get a newer version?

**Comment by audetto** [comment]
The problem is that as soon as I install `mxe-x86-64-w64-mingw32.static-boost` this installs the old gcc 5 as well.

**Comment by audetto** [comment]
The answer is here:

https://git.libretro.com/libretro-infrastructure/libretro-build-mxe-win-cross-cores/-/blob/fb98d96078250a582ada5d30ee67e503c4358250/Dockerfile.gcc11#L128

packages must not be installed via `apt` but built in the `mxe` checkout under `/usr/lib/mxe`

anyway, this project only needs `boost` header files not libraries.

**Comment by audetto** [comment]
OK, pushed a new commit, full instructions are

1. `make boost` in `/usr/lib/mxe` (takes 10-15 minutes)
2. `apt install xxd`
3. `cmake`... etc.

**Comment by audetto** [comment]
I am now able to cross-compile from Ubuntu inside VSCode using a mxe cmake kit.

Add this file to your `.vscode` folder

```
[
  {
    "name": "MXE",
    "toolchainFile": "/path/to/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake"
  }
]
```

It shows a warning, but works.

Then, you can just switch compiler in the VSCode status bar.

**Comment by gouchi** [comment]
We have a little [documentation](https://docs.libretro.com/development/cores/developing-cores/#add-your-core-to-libretro-infrastructure) about adding a Libretro core to the Libretro CI/CD.

So first, the core info file should be submitted to Libretro super repository then we should create `gitlab-ci.yml`.

@zoltanvb if you have the opportunity to make some compilation test.

Thank you.

**Comment by gouchi** [comment]
For now, I put "straightforward" `.gitlab-ci.yml`,we can extend it later on if we need some something specific build options for a platform  using for example

```
.core-defs-XXX:
  extends: .core-defs
  variables:
    CORE_ARGS: -DLIBRETRO=ON -DCMAKE_BUILD_TYPE=Release -DXXX
```

[Source](https://github.com/flyinghead/flycast/blob/master/.gitlab-ci.yml)

<details>
  <summary>.gitlab-ci.yml</summary>

```
# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CORENAME: applewin
    CORE_ARGS: -DBUILD_LIBRETRO=ON -DCMAKE_BUILD_TYPE=Release

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

  # MacOS
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-x86.yml'

  # MacOS
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-arm64.yml'

  # Linux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

  # DJGPP
  - project: 'libretro-infrastructure/ci-templates'
    file: '/djgpp-static-cmake.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-cmake.yml'

  ################################## CONSOLES ################################
  # Libnx
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static-cmake.yml'

  # CTR (3DS)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ctr-static-cmake.yml'

  # PSP
  - project: 'libretro-infrastructure/ci-templates'
    file: '/psp-static-cmake.yml'

  # PS2
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ps2-static-cmake.yml'

  # VITA
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static-cmake.yml'

  # WiiU
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static-cmake.yml'

  # tvOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-cmake.yml'

  # Dingux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-cmake.yml'

  # Wii
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wii-static-cmake.yml'

  # Gamecube
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ngc-static-cmake.yml'

  ################################## MISC ####################################
  # Emscripten
  - project: 'libretro-infrastructure/ci-templates'
    file: '/emscripten-static-cmake.yml' 

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-cmake-x86
    - .core-defs

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-cmake-x86

# MacOS 32-bit
libretro-build-osx-x86:
  extends:
    - .libretro-osx-cmake-x86
    - .core-defs

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-cmake-x86_64
    - .core-defs

# MacOS ARM64
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs

# DJGPP
libretro-build-djgpp-i586:
  extends:
    - .libretro-djgpp-static-cmake-retroarch-master
    - .core-defs

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-cmake-armeabi-v7a
    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-cmake-x86
    - .core-defs

# iOS arm64
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-cmake-arm64
    - .core-defs

# iOS armv7
libretro-build-ios9:
  extends:
    - .libretro-ios-cmake-ios9
    - .core-defs

################################### CONSOLES #################################
# Libnx
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-cmake-retroarch-master
    - .core-defs

# CTR (3ds)
libretro-build-ctr:
  extends:
    - .libretro-ctr-static-cmake-retroarch-master
    - .core-defs

# PSP
libretro-build-psp:
  extends:
    - .libretro-psp-static-cmake-retroarch-master
    - .core-defs

# PS2
libretro-build-ps2:
  extends:
    - .libretro-ps2-static-cmake-retroarch-master
    - .core-defs

# VITA
libretro-build-vita:
  extends:
    - .libretro-vita-static-cmake-retroarch-master
    - .core-defs

# tvOS arm64
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-cmake-arm64
    - .core-defs

# WiiU
libretro-build-wiiu:
  extends:
    - .libretro-wiiu-static-cmake-retroarch-master
    - .core-defs

# Dingux
libretro-build-dingux-mips32:
  extends:
    - .libretro-dingux-cmake-mips32
    - .core-defs

libretro-build-dingux-odbeta-mips32:
  extends:
    - .libretro-dingux-odbeta-cmake-mips32
    - .core-defs

libretro-build-rs90-odbeta-mips32:
  extends:
    - .libretro-rs90-odbeta-cmake-mips32
    - .core-defs

libretro-build-retrofw-mips32:
  extends:
    - .libretro-retrofw-odbeta-cmake-mips32
    - .core-defs

libretro-build-miyoo-arm32:
  extends:
    - .libretro-miyoo-cmake-arm32
    - .core-defs

# Wii
libretro-build-wii:
  extends:
    - .libretro-wii-static-cmake-retroarch-master
    - .core-defs

# Gamecube
libretro-build-ngc:
  extends:
    - .libretro-ngc-static-cmake-retroarch-master
    - .core-defs

################################### MISC #####################################

# Emscripten
libretro-build-emscripten:
  extends:
    - .libretro-emscripten-static-cmake-retroarch-master
    - .core-defs
```

</details>
